# Generated by Django 4.0.3 on 2022-03-19 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100, null=True)),
                ('ContactPerson', models.CharField(max_length=100, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Unique_number', models.IntegerField(null=True)),
                ('Fiscal_number', models.IntegerField(null=True)),
                ('Business_number', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Dateadded', models.DateTimeField(auto_now_add=True)),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deadline', models.DateField(null=True)),
                ('Dateadded', models.DateTimeField(auto_now_add=True)),
                ('DEPARTMENT', models.CharField(choices=[('PRESS', 'PRESS'), ('DESIGN', 'DESIGN')], max_length=100, null=True)),
                ('Comment', models.CharField(max_length=200, null=True)),
                ('TotalPrice', models.FloatField(null=True)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.clients')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(choices=[('FOLJE', 'FOLJE'), ('ALUBOND', 'ALUBOND')], max_length=100, null=True)),
                ('Machine', models.CharField(choices=[('MIMAKI', 'MIMAKI'), ('XEROX', 'XEROX')], max_length=100, null=True)),
                ('Dimension1', models.FloatField(null=True)),
                ('Dimension2', models.FloatField(null=True)),
                ('Quantity', models.FloatField(null=True)),
                ('project', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('Mount', models.BooleanField(null=True)),
                ('Comment', models.CharField(max_length=200, null=True)),
                ('CompanyName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.orders')),
            ],
            options={
                'verbose_name_plural': 'OrderItems',
            },
        ),
    ]
