# Generated by Django 4.0.3 on 2022-03-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_orders_status_alter_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='Business_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Fiscal_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='Unique_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
